indir: no  # to be overriden in CLI
outdir: no  # to be overriden in CLI

model:
  path: no  # to be overriden in CLI
  checkpoint: /home/ubuntu/lama/my_dataset/experiments/ubuntu_2022-05-27_12-46-30_train_big-lama_/models/last.ckpt

dataset:
  kind: default
  img_suffix: .png
  pad_out_to_modulo: 8

device: cuda
out_key: inpainted
