generator_kind: random

mask_generator_kwargs:
  irregular_proba: 0.5
  irregular_kwargs:
    max_angle: 4
    max_len: 400
    max_width: 400
    max_times: 5
    min_times: 1

  box_proba: 0.5
  box_kwargs:
    margin: 10
    bbox_min_size: 200
    bbox_max_size: 400
    max_times: 4
    min_times: 1

  segm_proba: 0
  outpainting_proba: 1
  outpainting_kwargs:
    min_padding_percent: 0.2
    max_padding_percent: 0.5

  variants_n: 5

max_masks_per_image: 1

cropping:
  out_min_size: 512
  handle_small_mode: upscale
  out_square_crop: True
  crop_min_overlap: 1

max_tamper_area: 0.5
